// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssessmentGPMAMVC.Models;

public partial class advice
{
    public int Id { get; set; }

    public string Text { get; set; }

    public string ImageUrl { get; set; }

    public string VideoUrl { get; set; }

    public int SectionId { get; set; }

    public virtual Section Section { get; set; }
}