// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AssessmentGPMA.Domain.models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssessmentGPMAMVC.Models;

public partial class QuestionFile
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public string ContentType { get; set; }

    public DateTime UploadedAt { get; set; }

    public int QuestionId { get; set; }
    [ForeignKey("AppUser")]
    [MaxLength(450)]
    
    public string UserId { get; set; }

    public virtual Question Question { get; set; }
    public virtual AppUser User { get; set; }

}