// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssessmentGPMAMVC.Models;

public partial class Question
{
    public int Id { get; set; }

    public string Text { get; set; }
    public string ChoiceA { get; set; }
    public string ChoiceB { get; set; }
    public string ChoiceC { get; set; }
    public string ChoiceD { get; set; }
    public int CorrectAnswer { get; set; } // A, B, C, D
    public string Explanation { get; set; }
    public int SectionId { get; set; }

    public virtual ICollection<QuestionFile> QuestionFiles { get; set; } = new List<QuestionFile>();

    public virtual Section Section { get; set; }

    public virtual ICollection<UserAnswer> UserAnswers { get; set; } = new List<UserAnswer>();
}