// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssessmentGPMAMVC.Models;

public partial class Section
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int RoadmapId { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual Roadmap Roadmap { get; set; }

    public virtual ICollection<advice> advices { get; set; } = new List<advice>();
}