// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AssessmentGPMAMVC.Models;

public partial class TestAttempt
{
    public int Id { get; set; }

    public string UserId { get; set; }


    public DateTime StartedAt { get; set; }

    public double? Score { get; set; }
    public List<int?> ScoreForSection { get; set; }


    public virtual ICollection<UserAnswer> UserAnswers { get; set; } = new List<UserAnswer>();


}