// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AssessmentGPMA.Domain.models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssessmentGPMAMVC.Models;

public partial class UserAnswer
{
    public int Id { get; set; }

    public int? AttemptId { get; set; }
    [ForeignKey("AppUser")]
    public string UserId { get; set; }

    public int? QuestionId { get; set; }

    public int Answer { get; set; }


    public string fileURL { get; set; }

    public DateTime AnsweredAt { get; set; }

    public virtual TestAttempt Attempt { get; set; }

    public virtual Question Question { get; set; }

    public virtual AppUser User { get; set; }
}